[project]
name = "ptps-wildfire-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Aidan Feldman", email = "aidan.feldman@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "dask>=2026.7.1",
    "duckdb>=1.5.5",
    "icechunk>=1.1.21",
    "ipykernel>=7.3.0",
    "jupysql>=0.11.1",
    "lonboard>=0.16.0",
    "matplotlib>=3.11.1",
    "pandas-stubs>=3.0.5.260730",
    "pyarrow>=25.0.0",
    # for JupySQL
    "toml>=0.10.2",
    "xarray>=2026.7.0",
]
